version: '3.4'

services:
    nginx:
        # @see https://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-nginx-dev.html#customization
        image: webdevops/php-nginx-dev:8.2
        user: "1000:1000"
        volumes:
            - ./:/app
            - ./.docker/nginx/conf.d/default.conf:/opt/docker/etc/nginx/vhost.conf
        working_dir: /app
        environment:
            # PHP config
            # @see https://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-nginx-dev.html#environment-variables
            PHP_DATE_TIMEZONE: "Europe/Paris"
            PHP_DISPLAY_ERRORS: "on"
            PHP_MAX_EXECUTION_TIME: 7200
            PHP_OPCACHE_REVALIDATE_FREQ: 0
            php.xdebug.var_display_max_depth: 10
            php.xdebug.var_display_max_data: 2048
        deploy:
            labels:
                - traefik.enable=true

                - traefik.http.services.changy.loadbalancer.server.port=80

                - traefik.http.routers.changy.rule=Host(`changy-archives.local.barlito.fr`)
                - traefik.http.routers.changy.entrypoints=http
                #- traefik.http.routers.changy.middlewares=tls-redirectscheme

                - traefik.http.routers.changy-secure.rule=Host(`changy-archives.local.barlito.fr`)
                - traefik.http.routers.changy-secure.entrypoints=https
                - traefik.http.routers.changy-secure.tls=true
        networks:
            - traefik_traefik_proxy

networks:
    traefik_traefik_proxy:
        external: true
