version: '3.4'

services:
    nginx:
        # @see https://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-nginx-dev.html#customization
        image: webdevops/php-nginx-dev:8.2
        user: "1000:1000"
        volumes:
            - ./:/app
            - ./.docker/nginx/conf.d/default.conf:/opt/docker/etc/nginx/vhost.conf
            - ~/.composer:/root/.composer:delegated
        working_dir: /app
        environment:
            # PHP config
            # @see https://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-nginx-dev.html#environment-variables
            PHP_DATE_TIMEZONE: "Europe/Paris"
            PHP_DISPLAY_ERRORS: "on"
            PHP_MAX_EXECUTION_TIME: 7200
            PHP_OPCACHE_REVALIDATE_FREQ: 0
            php.xdebug.var_display_max_depth: 10
            php.xdebug.var_display_max_data: 2048
        deploy:
            labels:
                - traefik.enable=true

                - traefik.http.services.changy.loadbalancer.server.port=80

                - traefik.http.routers.changy.rule=Host(`changy-archives.local.barlito.fr`)
                - traefik.http.routers.changy.entrypoints=http
                #- traefik.http.routers.changy.middlewares=tls-redirectscheme

                - traefik.http.routers.changy-secure.rule=Host(`changy-archives.local.barlito.fr`)
                - traefik.http.routers.changy-secure.entrypoints=https
                - traefik.http.routers.changy-secure.tls=true
        networks:
            - changy_internal
            - traefik_traefik_proxy

    db:
        image: postgres:13
        environment:
            POSTGRES_PASSWORD: root
        volumes:
            - changy_db_data:/var/lib/postgresql/data:rw
        networks:
            - changy_internal

    adminer:
        image: adminer
        deploy:
            labels:
                - traefik.enable=true

                - traefik.http.services.changy_adminer.loadbalancer.server.port=8080

                - traefik.http.routers.changy_adminer.rule=Host(`changy-archives-adminer.local.barlito.fr`)
                - traefik.http.routers.changy_adminer.entrypoints=http

                - traefik.http.routers.changy_adminer-secure.rule=Host(`changy-archives-adminer.local.barlito.fr`)
                - traefik.http.routers.changy_adminer-secure.entrypoints=https
                - traefik.http.routers.changy_adminer-secure.tls=true
        networks:
            - changy_internal
            - traefik_traefik_proxy

volumes:
    changy_db_data:

networks:
    traefik_traefik_proxy:
        external: true
    changy_internal:
        driver: overlay
